version: '3'

services:
  web:
    image: nginx
    platform: linux/amd64
    depends_on:
      - php
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./yii-app:/var/www/html
    ports:
      - "8081:80"

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    platform: linux/amd64
    working_dir: /var/www/html/WebRoot
    volumes:
      - ./yii-app:/var/www/html

  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yii_db
      MYSQL_USER: yii_user
      MYSQL_PASSWORD: yii_password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db_data:/var/lib/mysql

volumes:
  db_data:
